In [248]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

# Part I: Preprocessing

## Basic Setups

In [249]:
import os
import sys
import warnings

import numpy as np
import pandas as pd
import sklearn
import lightgbm as lgb
import shap

warnings.filterwarnings("ignore")

In [250]:
import sys
from pathlib import Path

sys.path.append(str(Path.cwd().parent / "src"))

In [251]:
from utils.data_generator import check_missing_value, filling_missing_value_with_mean, filling_missing_value_with_median

In [252]:
DATA_DIR="../data"

## Load and Clean Data

In [253]:
df_sales_2016=pd.read_csv(os.path.join(DATA_DIR, "2016_sales.csv"))
df_sales_2017=pd.read_csv(os.path.join(DATA_DIR, "2017_sales.csv"))
df_weather=pd.read_csv(os.path.join(DATA_DIR, "weather_data.csv"))

In [254]:
# Combine sales data
df_sales=pd.concat([df_sales_2016, df_sales_2017], ignore_index=True)

# Convert date columns to datetime
df_sales["date"] = pd.to_datetime(df_sales["date"])
df_weather["date"] = pd.to_datetime(df_weather["date"])

## Handling missing values

### Checking missing values

In [255]:
check_missing_value(df_sales)

            count  percentage
date            0         0.0
province        0         0.0
store_id        0         0.0
store_name      0         0.0
category        0         0.0
item_id         0         0.0
item_name       0         0.0
sales        2009         1.0

### Filling missing values with median

In [ ]:
# Fill missing values with mean 
df_sales_filled=filling_missing_value_with_median(df_sales)

In [ ]:
# Check missing values again after filling
check_missing_value(df_sales_filled)

            count  percentage
date            0         0.0
province        0         0.0
store_id        0         0.0
store_name      0         0.0
category        0         0.0
item_id         0         0.0
item_name       0         0.0
sales           0         0.0